sonar.projectKey=richellemm_taskflow-devops
sonar.organization=richellemm
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/src/tests
sonar.test.inclusions=**/*.spec.js,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8